### ISSUE TITLE
Detect and display sponsor affiliation

### ISSUE THREAD

**Issue by ryanprice** [ryanprice/Cryptoz.cards-Dapp#51]
This will be accomplished by detecting the url, something like 

Click my sponsor link , can be sent around to people or shared etc. hmm maybe we need a redirect or some way to shorten this, ?
https://rinkeby.cryptoz.cards/?sponsor=0xBc9541xxxxxxxxxxxxxxxxxxxxxxxxxx703

the app will detect the anchor in the url and present a modal explaining that they can link the sponsor and Earn a Platinum Sponsored Card. When they click the button it will call contract.linkMySponsor(address mySponsor)

and emit  the LogSponsorLinked(address sponsor, address affiliate)  event

**Comment by mchigit** [comment]
@ryanprice Just want to verify with you the behavior of this issue so I don't misunderstand it. 

Basically we will have a button/link somewhere (possibly in the header) called `Get My Sponsor Link` and by clicking it we will generate a link like above `https://rinkeby.cryptoz.cards/?sponsor=0xBc9541xxxxxxxxxxxxxxxxxxxxxxxxxx703` or a shortened version of this, then they can send this link to others. 

For users who go to the app with this link:
- detect the address of sponsor, open up a modal
- Modal will explain how sponsor works, and with a button "Link My Sponsor"
- Call the functions after clicking confirm

Questions: 
1. This modal popup should be after verifying the user is logged in using MetaMask right? Because we need the affiliate's address for `LogSponsorLinked`. Or we can have the modal pop up but have the content as you need to login and have the connect button there
2. Do we need to redirect user? Do they get the sponsor card instantly? If so we should probably redirect them to their Crypt page?

**Comment by ryanprice** [comment]
> Questions:
> 
> 1. This modal popup should be after verifying the user is logged in using MetaMask right? Because we need the affiliate's address for `LogSponsorLinked`. Or we can have the modal pop up but have the content as you need to login and have the connect button there

correct, because the contract function linkMySponsor(sponsor_wallet_address) actually detects the submitter's wallet address and uses it to create the association. This ensures that only the affiliate wallet can request the binding to the sponsor.

> 2. Do we need to redirect user? Do they get the sponsor card instantly? If so we should probably redirect them to their Crypt page?

Yes that would be excellent, redirect to the crypt to see their new card. The contract will automatically mint that for them.

**Comment by ryanprice** [comment]
great job , it's closed now
